helloworld:
	go build helloworld.go

echo:
	go build echo_1.go

echo_2:
	go build echo_2.go

echo_3:
	go build echo_3.go

dup_1:
	go build dup_1.go

dup_2:
	go build dup_2.go

dup_3:
	go build dup_3.go

lissajous:
	go build lissajous.go

fetch:
	go build fetch.go

fetchall:
	go build fetchall.go

server_1:
	go build server_1.go

clean:
	rm -f helloworld
	rm -f echo_1 echo_2 echo_3
	rm -f dup_1 dup_2 dup_3
	rm -f lissajous
	rm -f fetch fetchall
	rm -f server_1